version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    environment:
      - DOCKER_REGISTRY: 'quay.io/wework'
      - DOCKER_REPOSITORY: 'quay.io/wework/go_project_layout'
    working_directory: /go/src/github.com/WeConnect/go_project_layout
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: DockerLogin
          command: .circleci/docker_login
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run:
          name: CIBuild
          command: script/cibuild

workflows:
  version: 2
  cibuild:
    jobs:
      - build:
          context: org-global
