#!/bin/sh
set -e

if [ -z ${QUAY_ROBOT_USER} ]; then
    echo "quay user is empty. Could not proceed to docker login"
    exit 1
fi

if [ -z ${QUAY_TOKEN} ]; then
    echo "quay token is empty. Could not proceed to docker login"
    exit 1
fi

docker login -u="$QUAY_ROBOT_USER" -p="$QUAY_TOKEN" quay.io
